global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  - job_name: 'vector-internal'
    static_configs:
      - targets: ['vector:9092']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'vector-claude-code'
    static_configs:
      - targets: ['vector:9091']
    scrape_interval: 5s
    metrics_path: /metrics